### ISSUE TITLE
Extend the list for newer SQL Server versions

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#107]
the newest version in the list is:
SQL Server 2016	C:\Windows\SysWOW64\SQLServerManager13.msc
you could add
SQL Server 2017	C:\Windows\SysWOW64\SQLServerManager14.msc
and so on, depending on the right names

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 24e49fc4-1101-0d6f-e16a-52242616287b
* Version Independent ID: df5e0042-2137-3309-a957-de5f556f5c84
* Content: [Lektion 2: Herstellen einer Verbindung von einem anderen Computer - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/lesson-2-connecting-from-another-computer?view=sql-server-ver15)
* Content Source: [docs/relational-databases/lesson-2-connecting-from-another-computer.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/lesson-2-connecting-from-another-computer.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MashaMSFT** [comment]
Hi @aisbergde , thank you so much for your feedback! You're right, this would be helpful to add.  Did you want to make the edit yourself? If you do so, you will be added as a contributor to the article :)

To do so, please do the following:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

If you'd like, please feel free to submit the pull request to make this change. Otherwise, I can process this change myself.

Thanks!
Masha from the SQL Docs team

**Comment by aisbergde** [comment]
Good idea, I did not know that I am allowed.
