### ISSUE TITLE
sp_update_job @notify_level_email valid values wrong

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/sql-docs.de-de#109]
The description for parameter @notify_level_email is wrong.
Value 0 for 'Never' is not supported. The error message is:
> The specified '@notify_level_email' is invalid (valid values are: 1, 2, 3).

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b7c3735b-36b2-f19e-c4ce-41e6ce3e277f
* Version Independent ID: 0af58b01-c988-dbeb-f9d6-c2214f348aa9
* Content: [Sp_update_job (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/system-stored-procedures/sp-update-job-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-update-job-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/system-stored-procedures/sp-update-job-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @abbgrade
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @abbgrade 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3380

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
