### ISSUE TITLE
yum repro path not correct

### ISSUE THREAD

**Issue by tire0011** [MicrosoftDocs/sql-docs.de-de#84]
curl https://packages.microsoft.com/config/rhel/7/prod.repo &gt; /etc/yum.repos.d/msprod.repo
should be 
curl https://packages.microsoft.com/config/rhel/7/prod.repo &gt; /etc/yum/repos.d/msprod.repo

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Installieren von SQL Server-Befehlszeilentools unter Linux - SQL Server](https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2279](https://github.com/MicrosoftDocs/sql-docs/issues/2279) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @tire0011 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/2279

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
