### ISSUE TITLE
Is the operand table valid?

### ISSUE THREAD

**Issue by Tornhoof** [MicrosoftDocs/sql-docs.de-de#85]
In the table above, bigint is not listed in the right operands of bigint, the description does not exclude it though and something like this:
```sql
declare @rside as bigint
declare @lside as bigint
set @lside = 922337203685477580
set @rside = 9223372036854775807
SELECT ( @lside & @rside)
GO
```
works in SQL Server 2017. 
You might want to rework the table, either you properly list all valid combinations, then you have a NxM matrix or you just describe the exceptions.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b730b2bb-57ee-aba8-247f-0fa63114c88b
* Version Independent ID: 36fd9a35-e182-a272-a9f4-f2da1eec7d17
* Content: [Bitweise Operatoren (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/language-elements/bitwise-operators-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/bitwise-operators-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/language-elements/bitwise-operators-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by CeciAc** [comment]
Hello, @Tornhoof

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/2293

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
